version: '3.8'
services:
  blackbox:
    image: bitnami/elasticsearch-exporter:1.5.0
    container_name: elasticsearch_exporter
    restart: always
    privileged: true
    network_mode: host
    pid: host
    command:  --es.uri=http://192.168.10.2:9200
