---
monitor:
    thanos_query:
      hosts:
        - 192.168.0.26:19192
        - 192.168.0.27:19192
    thanos_rule:
      hosts:
        - 192.168.0.26
    prometheus:
       hosts:
         - 192.168.0.26:19090
         - 192.168.0.24:19090
       external_labels:
         replica:  192.168.0.26
         monitor:  base
    alertmanager:
      hosts:
        - 192.168.0.26:9093
      web_hook:
        - url: http://127.0.0.1:8088/alertmessager/alert
    grafana:
      hosts:
        - 192.168.0.26
      root_url: "http://grafana.localhost.com"
    localhost:
        ip: 192.168.0.26


