{
 "title": "各业务集群资源使用总览",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterType", "label": "集群类型", "query": "label_values(up,cluster)" },
   { "name": "interval", "label": "统计周期", "query": "1h,6h,12h,1d,7d" },
   { "name": "threshold_min", "label": "阀值_下限", "query": "10" },
   { "name": "threshold_max", "label": "阀值_上限", "query": "80" },
   { "name": "threshold", "label": "阀值", "query": "10,30,50,85,95,100" },
   {
    "name": "YarnNode",
    "label": "YarnNode",
    "query": "label_values(bigdata_process_cpu_percent{name =\"NodeManager\", cluster=\"$ClusterType\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "资源使用率概览--$ClusterType", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "集群机器资源平均使用率",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg((1 - avg_over_time(node_memory_MemFree_bytes{cluster=~\"$ClusterType\"}[$interval])/avg_over_time(node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}[$interval])) * 100)",
     "legendFormat": "mem_used_cached"
    },
    {
     "expr": "avg((1 - avg_over_time(node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}[$interval])/avg_over_time(node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}[$interval])) * 100)",
     "legendFormat": "mem_used_no_cached"
    },
    {
     "expr": "(1- sum(node_filesystem_free_bytes{device=~\".+sd[b-m].*\",cluster=~\"$ClusterType\"}) by (cluster)/sum(node_filesystem_size_bytes{device=~\".+sd[b-m].*\",cluster=~\"$ClusterType\"}) by (cluster) )* 100",
     "legendFormat": "disk_used"
    },
    {
     "expr": "avg((1- sum(avg_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100)",
     "legendFormat": "cpu_use_avg"
    },
    {
     "expr": "avg((1- sum(max_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100)",
     "legendFormat": "cpu_use_min"
    },
    {
     "expr": "avg((1- sum(min_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100)",
     "legendFormat": "cpu_use_max"
    }
   ]
  },
  {
   "title": "机器总数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cpucores{cluster=~\"$ClusterType\"})"
    },
    {
     "expr": "count(windows_cpucores{cluster=~\"$ClusterType\"})"
    }
   ]
  },
  {
   "title": "cpu总核数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpucores{cluster=~\"$ClusterType\"}) "
    }
   ]
  },
  {
   "title": "内存总数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"})"
    }
   ]
  },
  {
   "title": "磁盘总数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=~\"$ClusterType\"})"
    }
   ]
  },
  { "title": "集群业务指标--$ClusterType", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "大数据各类服务节点个数",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(bigdata_process_cpu_percent{cluster=~\"$ClusterType\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "集群整体 CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}) by(cluster) / sum(cpucores{cluster=~\"$ClusterType\"}) by(cluster)) * 100",
     "legendFormat": "集群整体CPU使用率"
    },
    {
     "expr": "(1 - sum(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\",instance=~\"$YarnNode\"}) by(cluster) / sum(cpucores{cluster=~\"$ClusterType\",instance=~\"$YarnNode\"}) by(cluster)) * 100",
     "legendFormat": "Yarn 集群整体CPU使用率"
    }
   ]
  },
  {
   "title": "集群整体 CPU Load(5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load5{cluster=~\"$ClusterType\"}) by (cluster)",
     "legendFormat": "集群整体 CPU load"
    },
    {
     "expr": "sum(node_load5{cluster=~\"$ClusterType\",instance=~\"$YarnNode\"}) by (cluster)",
     "legendFormat": "Yarn节点 CPU load"
    }
   ]
  },
  {
   "title": "集群整体 Disk space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1- sum by(cluster)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(cluster)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100"
    }
   ]
  },
  {
   "title": "集群整体磁盘 IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{cluster=~\"$ClusterType\",device=~\"vd[a-m].*\"}[5m])) by (cluster)",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{cluster=~\"$ClusterType\",device=~\"vd[a-m].*\"}[5m])) by (cluster)",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "集群整体 Memory Usage(no cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1- sum(node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}) by (cluster)/sum(node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}) by (cluster)) * 100 "
    }
   ]
  },
  {
   "title": "集群整体网卡流量情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{cluster=~\"$ClusterType\",device=~\"(eth0|eth1)\"}[2m])) by (cluster) *8",
     "legendFormat": "send"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{cluster=~\"$ClusterType\",device=~\"(eth0|eth1)\"}[2m])) by (cluster) *8",
     "legendFormat": "receive"
    }
   ]
  },
  { "title": "硬件资源使用率--$ClusterType", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU 最大使用率分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 44 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((1- sum(min_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100 < $threshold_min)",
     "legendFormat": "< $threshold_min%"
    },
    {
     "expr": "count((1- sum(min_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100 >= $threshold_min and 50 >(1- sum(min_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100)",
     "legendFormat": "$threshold_min% ~ 50%"
    },
    {
     "expr": "count((1- sum(min_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100 >= 50 and $threshold_max >(1- sum(min_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100)",
     "legendFormat": "50% ~ $threshold_max%"
    },
    {
     "expr": "count((1- sum(min_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100 >= $threshold_max)",
     "legendFormat": "> $threshold_max%"
    }
   ]
  },
  {
   "title": "Memory 实时使用率分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 44 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((1- node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}/node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}) * 100 < $threshold_min)",
     "legendFormat": "< $threshold_min%"
    },
    {
     "expr": "count((1- node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}/node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}) * 100 >= $threshold_min and 50 > (1- node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}/node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}) * 100) ",
     "legendFormat": "$threshold_min% ~ 50%"
    },
    {
     "expr": "count((1- node_memory_MemAvailable_bytes{cluster=\"$ClusterType\"}/node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}) * 100 >= 50 and $threshold_max > (1- node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}/node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}) * 100) ",
     "legendFormat": "50% ~ $threshold_max%"
    },
    {
     "expr": "count((1- node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}/node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}) * 100 >= $threshold_max)",
     "legendFormat": "> $threshold_max%"
    }
   ]
  },
  {
   "title": "DISK 实时使用率分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 44 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100 < $threshold_min)",
     "legendFormat": "< $threshold_min%"
    },
    {
     "expr": "count((1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100 >=$threshold_min and 50 >(1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=\"$ClusterType\"}))* 100) ",
     "legendFormat": "$threshold_min% ~ 50%"
    },
    {
     "expr": "count((1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100 >=50 and $threshold_max >(1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100) ",
     "legendFormat": "50% ~ $threshold_max%"
    },
    {
     "expr": "count((1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100 >= $threshold_max)",
     "legendFormat": "> $threshold_max%"
    }
   ]
  },
  {
   "title": "cpu使用率不足$threshold_min%",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sort((1- sum(avg_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100 < $threshold_min)"
    }
   ]
  },
  {
   "title": "内存使用率不足$threshold_min%",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sort(avg by (hostname) ((1- avg_over_time(node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}[$interval])/avg_over_time(node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}[$interval])) * 100 < $threshold_min))"
    }
   ]
  },
  {
   "title": "硬盘使用率不足$threshold_min%",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 44 },
   "targets": [
    {
     "expr": "sort((1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100 < $threshold_min)"
    }
   ]
  },
  {
   "title": "$ClusterType cluster 磁盘使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{cluster=~\"$ClusterType\",device=~\".+vd[b-m].*\"}) by(cluster,hostname,device)) by (cluster) ",
     "legendFormat": "Total()"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{cluster=~\"$ClusterType\",device=~\".+vd[b-m].*\"} - node_filesystem_avail_bytes{cluster=~\"$ClusterType\",device=~\".+v[b-m].*\"}) by(cluster,hostname,device)) by (cluster)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "$ClusterType cluster 磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$ClusterType\",device=~\".+vd[b-m].*\"}) by (cluster) / sum(node_filesystem_size_bytes{cluster=\"$ClusterType\",device=~\".+vd[b-m].*\"}) by (cluster) * 100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "cpu使用率超过 $threshold_max%",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sort((1- sum(avg_over_time(cpu5musedrate{cluster=~\"$ClusterType\",mode=\"idle\"}[$interval])) by(hostname)/sum(cpucores{cluster=~\"$ClusterType\"}) by(hostname)) * 100 > $threshold_max)"
    }
   ]
  },
  {
   "title": "内存使用率超过 $threshold_max%",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "sort(avg by (hostname) ((1- avg_over_time(node_memory_MemAvailable_bytes{cluster=~\"$ClusterType\"}[$interval])/avg_over_time(node_memory_MemTotal_bytes{cluster=~\"$ClusterType\"}[$interval]) ) * 100 > $threshold_max))"
    }
   ]
  },
  {
   "title": "硬盘使用率超过 $threshold_max%",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 51 },
   "targets": [
    {
     "expr": "sort((1- sum by(hostname)(node_filesystem_free_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"})/sum by(hostname)(node_filesystem_size_bytes{device=~\".+vd[b-m].*\",cluster=~\"$ClusterType\"}))* 100 > $threshold_max)"
    }
   ]
  }
 ]
}