{
 "title": "节点资源面板",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d,90s"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_boot_time_seconds,cluster)"
   },
   {
    "name": "address",
    "label": "address",
    "query": "label_values(node_boot_time_seconds{cluster=\"$cluster\"}, ip_address)"
   },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds{ip_address=\"$address\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "机器硬件资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$server:.+\",name=~\".+\"})"
    }
   ]
  },
  {
   "title": "CPU CORE",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cpucores{instance=~\"$server:.+\"}"
    }
   ]
  },
  {
   "title": "内存",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:.+\"}  - node_memory_MemAvailable_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "数据磁盘",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{instance=~\"$server:.+\",device=~\".+vd[b-m].*|.+sd[b-m]\"}) by (instance)",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$server:.+\",device=~\".+vd[b-m].*|.+sd[b-m]\"}) by (instance) - sum(node_filesystem_free_bytes{instance=~\"$server:.+\",device=~\".+vd[b-m].*|.+sd[b-m]\"}) by (instance)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "系统盘",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=~\"$server:.+\",device=~\"/dev/mapper/system-root|rootfs\"}) by (instance)",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$server:.+\",device=~\"/dev/mapper/system-root|rootfs\"}) by (instance) - sum(node_filesystem_avail_bytes{instance=~\"$server:.+\",device=~\"/dev/mapper/system-root|rootfs\"}) by (instance) ",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "Cpu  Network 资源监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,mode) (rate(node_cpu_seconds_total{instance=~\"$server:.+\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Cpu Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"}",
     "legendFormat": "1 min load"
    },
    {
     "expr": "node_load5{instance=~\"$server:.*\"}",
     "legendFormat": "5 min load"
    },
    {
     "expr": "node_load15{instance=~\"$server:.*\"}",
     "legendFormat": "15 min load"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "MemTotal"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "MemFree(cache  not include)"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "Buffers"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$server:.+\",device=~\"(eth0|eth1|ens192)\"}[2m]) *8",
     "legendFormat": "receive {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$server:.+\",device=~\"(eth0|eth1|ens192)\"}[2m]) *8",
     "legendFormat": "send {{device}}"
    }
   ]
  },
  {
   "title": "网卡速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$server:.+\",device=\"eth0\"}[2m]) / 2500000000  > 0",
     "legendFormat": "{{device}}  receive"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$server:.+\",device!~\"eth.*|veth.*|lo|docker.*\"}[2m]) / 1250000000  > 0",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$server:.+\",device=\"bond0\"}[2m]) / 2500000000  > 0",
     "legendFormat": "{{device}} transmit"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$server:.+\",device!~\"bond0.*|veth.*|lo|docker.*\"}[2m]) / 1250000000  > 0",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "TCP 报文",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$server:.+\"}[2m])",
     "legendFormat": " 接收的 SYN cookies 的数量"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$server:.+\"}[2m])",
     "legendFormat": "无效的 SYN cookies 的数量"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$server:.+\"}[2m])",
     "legendFormat": "发送的 SYN cookies 的数量"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$server:.+\"}[2m])",
     "legendFormat": "队列连接丢弃数"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$server:.+\"}[2m])",
     "legendFormat": "从 LISTEN 状态直接转换到 SYN-RCVD 状态"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$server:.+\"}[2m])",
     "legendFormat": " socket 的队列溢出"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$server:.+\"}[5m])",
     "legendFormat": "TCP 接收的错误报文数"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$server:.+\"}[2m])",
     "legendFormat": "TCP 接收的目前所有建立连接的错误报文数"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$server:.+\"}[2m])",
     "legendFormat": "TCP 发送的报文数(2分钟内)"
    }
   ]
  },
  {
   "title": "网络连接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server:.+\",job=\"host\"} > 0",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Disk stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "磁盘读写次数频率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_writes_completed_total{instance=~\"$server:.+\",device!~'dm-*'}[5m]))",
     "legendFormat": "磁盘分区每秒写完成次数"
    },
    {
     "expr": "sum(irate(node_disk_writes_merged_total{instance=~\"$server:.+\",device!~'dm-*'}[5m]))",
     "legendFormat": "磁盘分区每秒合并写完成次数"
    },
    {
     "expr": "sum(irate(node_disk_reads_completed_total{instance=~\"$server:.+\",device!~'dm-*'}[5m]))",
     "legendFormat": "磁盘分区每秒读完成次数"
    },
    {
     "expr": "sum(irate(node_disk_reads_merged_total{instance=~\"$server:.+\",device!~'dm-*'}[2m]))",
     "legendFormat": "磁盘分区每秒合并读完成次数"
    }
   ]
  },
  {
   "title": "磁盘分区每秒读写的比特数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$server:.+\",device!~\"dm-*\"}[5m]))",
     "legendFormat": "磁盘分区每秒写入的比特数"
    },
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$server:.+\",device!~\"dm-*\"}[5m]))",
     "legendFormat": "磁盘分区每秒读取的比特数"
    }
   ]
  },
  {
   "title": "Disk read throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$server:.+\",device=~\"vd[a-m].*|sd[a-m]\"}[$interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$server:.+\",device=~\"vd[a-m].*|sd[a-m]\"}[$interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "read_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$server:.+\",device=~\"vd[a-m].*|sd[a-m]\"}[$interval])/60",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Throughout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$server:.+\",device=~\"vd[a-m].*|sd[a-m]\"}[$interval])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$server:.+\",device=~\"vd[a-m].*|sd[a-m]\"}[$interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "write_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$server:.+\",device=~\"vd[a-m].*|sd[a-m]\"}[$interval])/60",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem total file nodes  free  percent",
   "type": "graph",
   "description": "node_filesystem_files｛｝",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_files_free{instance=~'$server:.+',fstype=\"xfs\"} / node_filesystem_files{instance=~\"$server:.+\",fstype=\"xfs\"} ) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem size  free percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"xfs\",instance=~\"$server:.+\"} /node_filesystem_size_bytes{fstype=\"xfs\",instance=~\"$server:.+\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "内核相关指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "当前系统内存申请分配情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_CommitLimit_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "当前系统可申请总内存"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "当前已经申请的内存"
    },
    {}
   ]
  },
  {
   "title": "内存脏页和 vmalloc和ECC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "Dirty bytes"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "中毒页面 ECC 报错"
    },
    {
     "expr": "node_memory_VmallocChunk_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "VmallocChunk"
    },
    {
     "expr": "node_memory_VmallocTotal_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "VmallocTotal"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=~\"$server:.+\"}",
     "legendFormat": "VmallocUsed"
    },
    {}
   ]
  },
  {
   "title": "系统文件描述符",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$server:.+\"}",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "进程监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "进程监控",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(bigdata_process_cpu_percent{instance=~\"$server:.+\"}) by (name,pid)"
    },
    {
     "expr": "sum(bigdata_process_rss{instance=~\"$server:.+\"}) by (name,pid)"
    }
   ]
  },
  {
   "title": "容器监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "docker container cpu usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$server:.+\",id=~\"/docker/.*\"}[$interval])) by (name) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "docker container Mem usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum((container_memory_rss{instance=~\"$server:.+\",id=~\"/docker/.*\"})) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "容器资源分配表",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum(container_spec_memory_limit_bytes{instance=~\"$server:.+\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(container_memory_usage_bytes{instance=~\"$server:.+\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(container_spec_cpu_quota{instance=~\"$server:.+\",name=~\".+\"} / container_spec_cpu_period{instance=~\"$server:.+\",name=~\".+\"})  by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$server:.+\",name=~\".+\"}[$interval])) by (name) ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}