{
 "title": "进程监控",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ClusterType",
    "query": "label_values(up{type=\"node_exporter\"},cluster)"
   },
   {
    "name": "Node",
    "query": "label_values(up{type=\"node_exporter\",cluster=\"$ClusterType\"},instance)"
   },
   {
    "name": "process",
    "query": "label_values(bigdata_process_cpu_percent{instance=~\"$Node:.+\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "服务监控",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bigdata_process_up{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(bigdata_process_cpu_percent{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{name}}:{{pid}} "
    },
    {
     "expr": "cpucores{instance=~\"$Node:.+\"} * 100",
     "legendFormat": "CPU total"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(bigdata_process_rss{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{name}}:{{pid}}  物理内存"
    },
    {
     "expr": "sum(bigdata_process_vms{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{name}}:{{pid}} 全部内存"
    },
    {
     "expr": "bigdata_process_data{instance=~\"$Node:.+\",name=~\"$process\"}",
     "legendFormat": "{{name}}:{{pid}}  DATA"
    },
    {
     "expr": "bigdata_process_dirty{instance=~\"$Node:.+\",name=~\"$process\"}",
     "legendFormat": "{{name}}:{{pid}}  脏页"
    }
   ]
  },
  {
   "title": "进程端口连接详细",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bigdata_process_ESTABLISHED{instance=~\"$Node:.+\",name=~\"$process\"}) by (name,port)",
     "legendFormat": " {{name}} pid:{{pid}} port: {{port}}   establish"
    },
    {
     "expr": "sum(bigdata_process_CLOSE_WAIT{instance=~\"$Node:.+\",name=~\"$process\"})  by (name,port)",
     "legendFormat": " {{name}} pid:{{pid}}  port: {{port}} close_wait"
    }
   ]
  },
  {
   "title": "网络连接总计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bigdata_process_total_ESTABLISHED{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{name}}:{{pid}}  ESTABLISHED"
    },
    {
     "expr": "sum(bigdata_process_total_CLOSE_WAIT{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{name}}:{{pid}} CLOSE_WAIT"
    },
    {
     "expr": "sum(bigdata_process_total_TIME_WAIT{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "time wait"
    }
   ]
  },
  {
   "title": "文件描述符占用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bigdata_process_num_fds{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{name}} {{pid}} 文件描述符"
    },
    {
     "expr": "sum(bigdata_process_num_fds{instance=~\"$Node:.+\"})",
     "legendFormat": "所有进程加和："
    }
   ]
  },
  {
   "title": "process disk operation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bigdata_process_read_bytes{instance=~\"$Node:.+\",name=~\"$process\"}[2m])) by (name)",
     "legendFormat": "{{name}}:{{pid}} read"
    },
    {
     "expr": "sum(rate(bigdata_process_write_bytes{instance=~\"$Node:.+\",name=~\"$process\"}[2m])) by (name)",
     "legendFormat": "{{name}}:{{pid}} write"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bigdata_process_num_threads{instance=~\"$Node:.+\",name=~\"$process\"}) by (name)",
     "legendFormat": "{{name}} {{pid}} 线程数"
    }
   ]
  }
 ]
}